### ISSUE TITLE
sourceMap报脚本错误了

### ISSUE THREAD

**Issue by yoder** [WozHuang/try#5]
source-map.js:1939 Uncaught (in promise) Error: Line numbers must be >= 1
    at BasicSourceMapConsumer.originalPositionFor (source-map.js:1939)
    at source-map-viewer.html:56
    at source-map.js:1522

**Comment by liganghui** [comment]
你没有填  line:column   具体的 line:column   参考公众平台的报错信息

![微信截图_20191111102843](https://user-images.githubusercontent.com/15844198/68556656-1dbc1300-046e-11ea-99e6-5e906ee20bc2.png)
